### PR TITLE
Why read readme when you can just

### PR DESCRIPTION
**Pull request by Michcioperz**
`requirements.txt` is kind of a standard way of telling people pip requirements these days y'know
`pip install -r requirements.txt` and stuff

### CODE REVIEW

**Comment by iandioch** [comment]
requirements.txt is only for things you can install via pip, but tesseract-ocr isn't done through pip, and I had to play with apt-get to get Pillow (a dep of pyocr) installed. A requirements.txt seemed like more trouble than it was worth when neither dependency of the project fully worked with it. 

I thought about including an install bash script, but that'd only work for one distro; even different versions of ubuntu require different scripts to get Pillow.

What do you think? I will merge, but if you have any cooler ideas then shout

**Comment by Michcioperz** [comment]
Common sense would be looking up a few common distros and putting instructions in README
Arch Linux package seems to be just `tesseract` but I also had `tesseract-data-eng` and `tesseract-data-pol` installed at the point so no clue to an extent

**Comment by Michcioperz** [comment]
Oh by the way I'm totally sure Pillow can also be installed with pip so yeah well
Ooooh I know you could write a Dockerfile that would be universal y'know y'know

**Comment by iandioch** [comment]
In theory it can, but it doesn't officially support Linux, so some other dependencies need to be grabbed sometimes first from the OS repositories. 

A dockerfile seems like overkill for 1 little script, but I am curious... Yeah that'd be cool

**Comment by iandioch** [comment]
Will merge this, ty

**Pull request merged**
